#!/usr/bin/env node


// modules =================================================
var express        = require('express');
var app            = express();
var bodyParser     = require('body-parser');
var methodOverride = require('method-override');
var routing = require('./app/routes.js'); // configure our routes
var logsFunctionalities = require('./app/computation/readFiles.js'); // configure our routes


// configuration ===========================================

// set our port
var port = process.env.PORT || 3000;

// get all data/stuff of the body (POST) parameters
// parse application/json
app.use(bodyParser.json());

// parse application/vnd.api+json as json
app.use(bodyParser.json({ type: 'application/vnd.api+json' }));

// parse application/x-www-form-urlencoded
app.use(bodyParser.urlencoded({ extended: true }));

// override with the X-HTTP-Method-Override header in the request. simulate DELETE/PUT
app.use(methodOverride('X-HTTP-Method-Override'));

// set the static files location /public/img will be /img for users
app.use(express.static(__dirname + '/public'));

// functionalities ========================================
app.use(logsFunctionalities);
// routes ==================================================
app.use(routing);

// start app ===============================================
app.listen(port);


// expose app
exports = module.exports = app;